spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mfpay?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
wx:
#  appId: wxd898fcb01713c658
  appId: wxc89a623029f611e1
#  appId: wx22afdbb37ef00ed8
#  mchId: 1483469312
  mchId: 1596921721
#  mchId: 1358448002
#  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  mchKey: 7mdApPMfXddfWWbbP4DUaVYm2wjyh3v3
  notifyUrl: http://mf-mall.natapp1.cc/pay/notify
#  notifyUrl: http://mamppro.com/en/order-history
#  returnUrl: http://127.0.0.1
  returnUrl: http://mamppro.com/en/order-history
alipay:
#  appId: 9021000135622197
#  privatekey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCe7E0Yn9WoaXQofyn5AsXQzhA0jLvHyo1zzBKk+AdPZWISMvXwsMaSSHznoUE1MJfe3pE9NRm7BzGSVQrJu4Z+VhnGpz9lxyVRtYjvb4FBBJLbZX6bfnhlgJkxcXHzE3bcTvnSAPif0KtTBk8MEIfIALB4N9TO/9WrRvLLnnC/EDEcDGfNxrYRqV0aLUaAa8w1UavEElmiMze2a9/351s+XxWqEzkTT6MXpBWvue+fJ5qzFD4bgiNPLGyo4amCBf0EF3inLPR8LeWNF+KomgGCq++SRZ4JUCxWxHuyRkEG249IJNiQpVA048OsAffzsPiUwrujnLLuxORca9teow5TAgMBAAECggEAUDWpj7UUDAT1WH8d+wz4NDPcn/kryWGk1P35pwN8BQmBXvgTgyBliG1HhUyw8ZyN+jFREphbXTb7QQTlBf48mkTwi3/cEo1Ze4zpCRe5H8ykJlFqfiZts6UdLIQ6Y9m+EuFVWzWcRmT2I1g6yzcIoNwgNPzQzoz3FZQgdL6J3xQJrkJMUKcEraOzjOZ+f17AlpVxtDuSPF5cGZQ5PHb/N6t4l037bmmCYVpuN+iaoynLWmfU7Nj+PwNM/SAMcQXqOHub0AWhF/JLrkGI1Uxmr1htiH6LPw4EB5Onc4wdUZD+cDurLsHb1Ltngj4FypMkOrs18AbQiWJ66TrrmEF+sQKBgQDtlGIu8AUwWvOXSfc5u8SnDPycdSwvtRXJ5yWKL/ux79QpotReyQ65drIiSflkXky+57EOePKFvG790rbS0+VWs8oHEFMgk9fsM8R5KjeSR8Y0epsfVan85rQc2M3SLZl5lZmyShkPwHEFBg/B0N0neLAlazE2s9NubcxvarXtmQKBgQCrPrJp8WF6531B3YnJ0okhsgSc76WO81sr0rFvmjWLlPeJTgTa1CobGcqZQLBfM6nXGFURDwP2hAPiwXq0venUKtBJIz4Hx/VbVa3JJc3OEHfuZfdRwvC/RadiPONNIUuO0bG8S4oebWlDDwGHGDGfDSuuTc5abiPVu+4iSWiWywKBgENZ5Hev/ZiWwCWsh1SroXVGHjrwkMU5jeK+D4tcTPtFpRzkl1YDo5P6TUehNv04KoOYRT54FTDKmaCFYuTjw0lQEL7t5tL+dqD0kAdVa4mhpVPtShqY+2bBtF/VKowh9zdbrMW5cd9gS+oDrOXiIz/0W+NPvxTl59OPdvxDAS5JAoGAa0Ojh/79u3mjGQ3G0FeDNEsI3rCx+H/w/NtF740duyf9gdEP825wTXdzU1mU4J1A5o3EQyIvrkt1D6V30h0fiZmjzBw6L6+Nvb9GUzfN2SSxqu/N4jYEjRr5ROy0yExxwq0Q8swyYOrRw4Jzx4ZdFq6uTMlJ15Uj9y53dJyc2c8CgYAfTZ5i4LBB6NV6cRPtqjd94yBAI0RI8kUJV7FLh9l7yQ+hVgfHuvV5KpL/AFau8ug/OnL8FCWgXOEXXbPMMX2qu0mSB9H0CtSSD9j5NF/8W6KihTULE5NLkgp2MVVr8zBypIfTDbXCHIBFOj+cYklQ/+23n8vfbnVqznMIYeHMKA==
#  publickey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsvqvB+4wOhB1nnoecmuZJB+YtAMSZGaANSAlB9uoqEscPKN9wViyJ8FzNdOqs+lPxYsSc3FGyHAwNuxwdYsZnOy7P+VolRvXE6O7w4kdpHKqV7or7DqKh21d2vRz97pVSDoeP8UHaWKqTT+7NMUyn0MPXWg9Bu8IsglymlRG/FUTsyjYz3RcP0JXMlOLNbCYP4EMbJuQgsvuc5LK//O9xM/p8pTwPRkEJeizzpOh/ybCOFF26MBv6i6/zuus3h4SO0zOJlZoGXIODmbwbaX1tADgzUoyhSpMISRcYoJpW9gFyiH1CyhYtgOSENBNAcoOGm8u/Ro8tFuPzuLb/UoHYwIDAQAB
#  notifyurl: http://q94adc.natappfree.cc/alipay/notify
#  returnurl: http://127.0.0.1
  appId: 2018062960540016
  privateKey: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDUcbUUBaTJA4ngFx1xED2WHrkS4YCi3BRDPu/qU+MXj7VNy/ip+VKSK9aGPd2dRswkt/4DOoOxnnesJDcve+2W9y2gPoOdSVjGlEwTE6MqeB5f3l+RO9Kcb2zL4JwCRxlE0HHLeRdWtnmbelh1rg8zTFwGnoi1pbQajAT/FGDFqIpdI6FrEYbyeR/VNxFXIGK16Z7gfnWRnS4TP93O5ckcuaAcE8tqW16G7u41bKsnsv2149mucBM2hFSEVD/KcGYYke3pD7VpQdk0+WhxITSsa5I8DfSFRKokN7iJoKjYWjI4gN3fxFWLbymeIumoOWdJflwYI5oL+GdVIHfQ0ETLAgMBAAECggEBALaqurdnjuQkfcXIOlGAVGQjMKFycmgWcfnMQQAsdyRINe2Zx8tnDL+QoBm3UjmsqVWdOvVNt/TevCmwzh6vIYBgMsQJXKO+cG33D16L0Q1wUTW/gE7hsFtAV70J+TrgJXMNA/ufuBigN/oe/bbaHknOi4ZJhGUkALOe16D4xajNjHcYdvkfw5Zkv9nAt+GjFphe1lt35KIx6ahFzMcnzzHYy4ezDFdQWPkT7CqrL8Nh9KPm6Sjbzw2JP3RH91OU1q44gPj7yyLTs1oxt4gEqOgVnczJWXoH+eKRmxRoIvodnB4kf1W9LTzAc4Qs7OneDccvhrOoTD3MGhqW0poXZFkCgYEA6dxBCLnU5oeoctoltnh42DXCzEv/M/gkv9HMY/FFnuM6e0qU5EcFjQtTPRRW1S45ctZaHHhpGppHF7RG+okdALj4x2OC1NG9DL4HboVW3CJ4TzmEeZRkR+LWRWw7FA8eXefDBTC4ojAwqkmbvYP3dm6FjSfNBGYs43Wm6qKTcB0CgYEA6I5rPmAv6rB1BBXF8riNhuoDntbHFHOC9kCwuVJooDBBnxXNCqA9mTdnwE8hjgCgbO5lQkeeIRYiZwFYdCLPW78j6Np5CaX0/ZxcVSUQBFYc3d0e3po+rqpX6BGOj7qGhzDXvAs+HScu7ERy0Kbq6b/EbuLlR3oCKIGncGIaxAcCgYBJyWrjm+6mxgrKIjZf+mb2oQ/Tce8VsKe3tjRtHEVBOqTLHd8Yn6gKtpYO4Yn8PVd2+lb4QK247RCdVA5JIlX6UmJ8VtOC3qJtkM+7eWrMjjuzk4xO6Bkz7Uh6IwoI7DRCoMuRqau30MiqEguHoknEHl8ZCIPRbYOgSRDfW2h1qQKBgF9ODnFPphN+IVZ9PdRNAeMqgDVWO9wLwr38oPAx76LGY/44RwF1zgi+hgxv4YZ6h0RdJq5U/1773TltebyOj4BAAw1oi3YCxzYwID7co4XDbK0X85CykcGvGbuHhm8st/krcR4lVV1JM5esLYmI/nixGGWBIwl53OyQxffunJ19AoGBAOX9cBWFIWh5EHVXYvW90HRBQoo1AYtsdrxTedqrij6cWQms6ACeQZPd5O0V6/Lhz3Lw5NRnUl9MbzwOC7BBSBvhWwNzBOzFnaoOvBABa5nFZsdF5jSI3LJHbnxmMvxnKjCgogSGf+hfgR042b/WKDDBEA965MQJ59tCVhALD81z"
  publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtojdtkETo4OEsQLeyyPwtWK9ZqYJANq6jjXC74vk9n/r88yW577y7VdxcK9X/F/wvR7D8of7lndYdhg6xZro0eO2skPZTU+A549J7tfzahVbIBAS+x1WPFJwPtVrfBBvkwHL8PT+YnMcxKyBxOa6wo8fzJs1NgU1+qnDCpwUFyv59GUfdzBvTPL1fY3ZzvRHFHbapevVltbO/jNV0thb8dafmcJXl8lnjQy3XlH3eTH28tlVfqickacfRl/WSD8WN3dGgF7dTDKYfSR7YB7jsHe6VzoHM3UnD9/yQbi/Z3ZrL7yOxEjq4tfrKlZIW7ZCoUpOU4QdPIRhLeC6nWyGrQIDAQAB"
  notifyUrl: http://mf-mall.natapp1.cc/pay/notify
  returnUrl: http://127.0.0.1


#http://localhost:8080/pay/create?orderId=1234567891234762&amount=0.01&payType=WXPAY_NATIVE


